### ISSUE TITLE
[Suggestion] Release prebuilt binary

### ISSUE THREAD

**Issue by Mammad900** [Muaath5/AutoReplyUserBot#1]
As a user, I want to be able to just download the binary and run it.  
Opening Visual Studio and compiling the program can be cumbersome, especially if the user doesn't have Visual Studio installed. (As you know Visual Studio is a heavy app and it takes gigabytes of storage and data, and takes hours to install)
This isn't something the general public likes to do.  
I suggest that the prebuilt binary/binaries be uploaded in the releases section.

**Comment by Muaath5** [comment]
Uploaded binaries for Windows x64 only, soon x86 will be added
